// file path: ~/DEVFOLD/ANUE-BACKEND/SRC/APP/LAYOUT.JS

import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./body/providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const appBarHeight = "3rem";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          width: "100vw",
          height: "100vh",
          // overflow: "scroll",
        }}
      >
        <Providers appBarHeight={appBarHeight}>{children}</Providers>
      </body>
    </html>
  );
}
