// file path: ~/DEVFOLD/ANUE-BACKEND/SRC/APP/LAYOUT.JS

import {
  Geist,
  Geist_Mono,
  Inter,
  Manrope,
  Montserrat,
  MuseoModerno,
  Plus_Jakarta_Sans,
  Poppins,
  Ubuntu,
  Urbanist,
} from "next/font/google";
import { Providers } from "./body/providers";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat", // Use this to link to your MUI theme
});
const museoModerno = MuseoModerno({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-museo-moderno", // Use this to link to your MUI theme
});
const ubuntu = Ubuntu({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "700"],
  variable: "--font-ubuntu", // Use this to link to your MUI theme
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} 
        ${geistMono.variable}
        ${montserrat.variable}
        ${museoModerno.variable}
        ${ubuntu.variable}
        `}
        style={{
          width: "100vw",
          height: "100vh",
          backgroundColor: "transparent",
        }}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
